#
# Module Manifest for:
# []Script Module | []Binary Module
#
# Generated by:
#
# Generated on:
#

@{
	RootModule             = 'VTStylizer.psm1'
	ModuleVersion          = '0.57.19'
	CompatiblePSEditions   = @('Core', 'Desktop')
	GUID                   = '3A185912-1879-4369-8410-73907E02E548'
	Author                 = 'Nathaniel Wallis Praytor'
	CompanyName            = 'Sierra Dream Studios'
	Copyright              = 'Copyright (c) 2021 Sierra Creative Workshop. All rights reserved.'
	Description            = 'PowerShell VT100 (Virtual Terminal) Ansi Escape Sequence Tokens for Output Format Styling.'
	HelpInfoUri            = ''
	#──────────────────────────────────────────────────────────────────────────────
	PowerShellVersion      = '5.1'
	PowerShellHostName     = ''
	PowerShellHostVersion  = ''
	DotNetFrameworkVersion = ''
	ClrVersion             = ''
	ProcessorArchitecture  = ''
	#──────────────────────────────────────────────────────────────────────────────
	RequiredModules        = @()
	RequiredAssemblies     = @()
	ScriptsToProcess       = @(
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.Base.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextFormatting.Styles.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextColorizer.ForegroundColors.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextColorizer.BackgroundColors.ps1'
	)
	TypesToProcess         = @()
	FormatsToProcess       = @()
	NestedModules          = @()
	#──────────────────────────────────────────────────────────────────────────────
	FunctionsToExport      = @(
		'Get-VTStyleOptions'
	)
	CmdletsToExport        = @()
	VariablesToExport      = @()
	AliasesToExport        = @()
	DscResourcesToExport   = @()
	DefaultCommandPrefix   = ''
	#──────────────────────────────────────────────────────────────────────────────
	ModuleList             = @()
	FileList               = @(
		'.\Public\Get-VTStyleOptions.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.Base.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextFormatting.Styles.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextColorizer.ForegroundColors.ps1',
		'.\Microsoft.PowerShell.VTStylizer.Tokens.ControlModifier.TextColorizer.BackgroundColors.ps1',
		'.\VTStylizer.psm1',
		'.\VTStylizer.psd1'
		)
	#──────────────────────────────────────────────────────────────────────────────
	PrivateData            = @{
		PSData = @{
			Tags                       = @('powershell', 'vt', 'virtual', 'terminal', 'ansi', 'escape', 'sequence', 'text', 'formatting', 'style', 'color')
			LicenseUri                 = 'http://www.apache.org/licenses/LICENSE-2.0.html'
			ProjectUri                 = 'https://github.com/SupernautFX/PowerShell.VTStylizer'
			IconUri                    = ''
			ReleaseNotes               = ''
			Prerelease                 = 'Alpha'
			RequireLicenseAcceptance   = $false
			ExternalModuleDependencies = @()
		}
	}
}